# Generated by Django 3.2.3 on 2021-05-13 11:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Genre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Zadejte knižní žánr (např. román, komedie)', max_length=50, unique=True, verbose_name='Název žánru')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
    ]
